[project]
name = "jpconjugation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Agtdbx", email = "auguste.deroubaix@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "jaconv>=0.5.0",
    "requests>=2.34.2",
]

[project.scripts]
jpconjugation = "jpconjugation:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
